### ISSUE TITLE
report for tidymodels objects

### ISSUE THREAD

**Issue by Aqvayli06** [easystats/report#163] opened 2021-04-28 18:05 UTC
I am working currently with tidymodels, and want to add on top of it a reporting module which automatically provides a nice and detailed report using your package, however it does not work using for the moment . :(

**Comment by IndrajeetPatil** [comment] 2021-04-28 18:25
Thanks for the feature request.

Duplicate of https://github.com/easystats/report/issues/122. Please track progress on this there.

**Closed by IndrajeetPatil** 2021-04-28 18:25 UTC
Labels: duplicate :two_men_holding_hands:
