### ISSUE TITLE
Is there  chisq.test full report as the t-test has , in which package ?

### ISSUE THREAD

**Issue by yliat123** [easystats/report#284] opened 2022-09-08 23:39 UTC
For t-test I get full report
================
> test <-t.test(SMOKERS,PATIENTS)
> report(test)
Effect sizes were labelled following Cohen's (1988) recommendations.

The Welch Two Sample t-test testing the difference between SMOKERS and PATIENTS (mean of x = 93.00, mean of
y = 99.25) suggests that the effect is negative, statistically not significant, and small (difference =
-6.25, 95% CI [-49.78, 37.28], t(6.00) = -0.35, p = 0.737; Cohen's d = -0.25, 95% CI [-1.63, 1.15])

For chisq.test not:
=============
> test <- chisq.test(table(dat$settings, dat$mm_phases))
> report(test)
Error: This test is not yet supported. Please open an issue: https://github.com/easystats/report/issues

**Comment by IndrajeetPatil** [comment] 2022-09-09 04:59
Hi,

Please don't create the same issue multiple times. You already created #283.

We are aware that chi-square test is not currently supported, and we plan to support it. There is also an open issue to track this: https://github.com/easystats/report/issues/258

Please be patient while work on this. Thanks.

**Comment by IndrajeetPatil** [comment] 2022-09-09 05:00
Duplicate of #283 and #258.

**Closed by IndrajeetPatil** 2022-09-09 04:59 UTC

**Comment by yliat123** [comment] 2022-09-09 06:21
Thanks
