### ISSUE TITLE
Feature request: 90% CI instead of 95%CI for Eta2 (partial)

### ISSUE THREAD

**Issue by XiaoyuZeng** [easystats/report#278] opened 2022-08-31 06:02 UTC
Dear developers,
**Describe the solution you'd like**
I have been convinced that we should report 90%CI, instead of 95%CI, for Eta2 (partial). Thus, I'm wondering whether it would be better to just report 90% CI in the _report_.

> Why should you report 90% CI for eta-squared?
Again, Karl Wuensch has gone out of his way to explain this in [a very clear document, including examples, which you can find here](http://core.ecu.edu/psyc/wuenschk/docs30/CI-Eta2-Alpha.doc). If you don’t want to read it, you should know that while Cohen’s d can be both positive and negative, r² or η² are squared, and can therefore only be positive. This is related to the fact that F-tests are always one-sided (so no, don’t even think about dividing that p = .08 you get from an F-test by two and reporting p = .04, one-sided). If you calculate 95% CI, you can get situations where the confidence interval includes 0, but the test reveals a statistical difference with a p < .05. For a paper by Steiger (2004) that addresses this topic,[ click here](http://www.statpower.net/Steiger%20Biblio/Steiger04.pdf). This means that a 95% CI around Cohen's d equals a 90% CI around η² for exactly the same test. Furthermore, because eta-squared cannot be smaller than zero, a confidence interval for an effect that is not statistically different from 0 (and thus that would normally 'exclude zero') necessarily has to start at 0. You report such a CI as 90% CI [.00; .XX]  where the XX is the upper limit of the CI. Confidence intervals are confusing intervals.

[http://daniellakens.blogspot.com/2014/06/calculating-confidence-intervals-for.html](url)

**How could we do it?**
A description of actual ways of implementing a feature.
I assumed this could be easily achieved by adjusting the CI from 95% to 90%. 

Many thanks in advance!

**Comment by mattansb** [comment] 2022-08-31 06:37
Hi @XiaoyuZeng ,

The 95% CI used for $\eta^2$ is a _one-sided_ CI (only the lower bound is estimated), so it still has the properties discussed in Laken's blog post - that of matching the NHST p-value.

This is more clear in `{effectsize}` - see the footnote:
``` r
m <- aov(mpg ~ factor(cyl), data = mtcars)

effectsize::eta_squared(m)
#> # Effect Size for ANOVA
#> 
#> Parameter   | Eta2 |       95% CI
#> ---------------------------------
#> factor(cyl) | 0.73 | [0.57, 1.00]
#> 
#> - One-sided CIs: upper bound fixed at [1.00].
```

<sup>Created on 2022-08-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

---


@DominiqueMakowski Maybe this information should be added to the text?

Current:

>  The main effect of factor(cyl) is statistically significant and large (F(2, 29) = 39.70, p < .001; Eta2 = 0.73, 95% CI [0.57, 1.00])

Suggestions:

> The main effect of factor(cyl) is statistically significant and large (F(2, 29) = 39.70, p < .001; Eta2 = 0.73, 95% CI **(one sided)** [0.57, 1.00])

Information about CI type is returned from `{effectsize}`:

```R
effectsize::eta_squared(m) |> 
  attr("alternative") # can be "two.sided", "greater", or "less"
#> [1] "greater"
```

**Comment by DominiqueMakowski** [comment] 2022-08-31 06:45
> Maybe this information should be added to the text?

yes, that would clarify things up

**Comment by mattansb** [comment] 2022-09-21 04:34
Duplicate of #205

**Closed by mattansb** 2022-09-21 04:34 UTC
Labels: phrasing :memo:
