### ISSUE TITLE
Error in `[.data.frame`(table, c("d", "d_CI_low", "d_CI_high")) : undefined columns selected

### ISSUE THREAD

**Issue by kiante-fernandez** [easystats/report#126] opened 2021-02-26 17:52 UTC
Love the package, I plan on giving a presentation on it and a few weeks and ran into an issue.

When I run: 

`report(t.test(mtcars$mpg ~ mtcars$am))`

I get: 

> "Error in `[.data.frame`(table, c("d", "d_CI_low", "d_CI_high")) : undefined columns selected"

**Expected behaviour**

I would expect the output to be the correct report as shown in the READ ME. I think the issue has something todo with
`report_effectsize.htest`. Though as I kept looking I am not so sure. 

**Specifiations**

Analyses were conducted using the R Statistical language (version 4.0.2; R Core Team, 2020) on macOS Catalina 10.15.7, 
report (version 0.2.0; Makowski et al., 2020)

**Comment by strengejacke** [comment] 2021-02-26 18:24
Looks like one or more of your easystats-packages are out of date. Could you please try updating your packages, or else post your session info?

**Comment by kiante-fernandez** [comment] 2021-02-26 20:14
I tried using the `easystats::easystats_update()` as well as updating the packages within easystats individually.
Here is the session information:

R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

attached base packages:
[1] stats     graphics  grDevices
[4] utils     datasets  methods  
[7] base     

other attached packages:
 [1] here_1.0.0         
 [2] modelbased_0.5.1   
 [3] correlation_0.6.0.1
 [4] effectsize_0.4.3-1 
 [5] see_0.6.2          
 [6] parameters_0.12.0.1
 [7] performance_0.7.0.1
 [8] bayestestR_0.8.3.1 
 [9] insight_0.13.1.1   
[10] easystats_0.2.0    
[11] report_0.2.0       
[12] forcats_0.5.0      
[13] stringr_1.4.0      
[14] dplyr_1.0.4        
[15] purrr_0.3.4        
[16] readr_1.4.0        
[17] tidyr_1.1.2        
[18] tibble_3.1.0       
[19] ggplot2_3.3.3      
[20] tidyverse_1.3.0

**Comment by DominiqueMakowski** [comment] 2021-02-26 23:59
![image](https://user-images.githubusercontent.com/8875533/109367565-5ab15080-78d1-11eb-8974-b0c3b9fb1e09.png)

Strange, it works for me, and we have the same `parameters` and `effectsize` version.

What happen when you run:

``` r
report::report_effectsize(t.test(mtcars$mpg ~ mtcars$am))
#> Effect sizes were labelled following Cohen's (1988) recommendations. 
#> 
#> large (Cohen's d = -1.41, 95% CI [-2.17, -0.51])
```

<sup>Created on 2021-02-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment] 2021-03-29 06:40
_bump_

**Comment by IndrajeetPatil** [comment] 2021-03-30 12:52
Can't reproduce this behavior with latest version:

``` r
library(report)
#> report is in alpha - help us improve by reporting bugs on github.com/easystats/report/issues
report(t.test(mtcars$mpg ~ mtcars$am))
#> Effect sizes were labelled following Cohen's (1988) recommendations.
#> 
#> The Welch Two Sample t-test testing the difference of mtcars$mpg by mtcars$am (mean in group 0 = 17.15, mean in group 1 = 24.39) suggests that the effect is positive, significant and large (difference = 7.24, 95% CI [-11.28, -3.21], t(18.33) = -3.77, p < .01; Cohen's d = -1.41, 95% CI [-2.17, -0.51])
```

<sup>Created on 2021-03-30 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

Closing this for now. 

@kiante-fernandez Please re-open if the issue persists for you even after updating the packages.

**Closed by IndrajeetPatil** 2021-03-30 12:52 UTC
Labels: waiting for response :love_letter:
