### ISSUE TITLE
Bug in `wilcox.test`

### ISSUE THREAD

**Issue by kisha126** [easystats/report#467] opened 2024-11-23 03:28 UTC
I don't know if it is only the `wilcox.test` function who got this kind of bug where 

```r
library(ISLR)
library(report)

> wilcox.test(wage ~ jobclass, data = Wage) |> 
+     report()
Could not compute effectsize NA.
  Possible reason: Unable to retrieve data from htest object.
  Try using
  'rb()' directly.
Error in UseMethod("interpret") : 
  no applicable method for 'interpret' applied to an object of class "NULL"
> with(Wage, wilcox.test(wage ~ jobclass)) |> 
+     report()
Could not compute effectsize NA.
  Possible reason: Unable to retrieve data from htest object.
  Try using
  'rb()' directly.
Error in UseMethod("interpret") : 
  no applicable method for 'interpret' applied to an object of class "NULL"
> Wage |> 
+     with(wilcox.test(wage ~ jobclass)) |> 
+     report()
Could not compute effectsize NA.
  Possible reason: Unable to retrieve data from htest object.
  Try using
  'rb()' directly.
Error in UseMethod("interpret") : 
  no applicable method for 'interpret' applied to an object of class "NULL"
``` 

it doesn't properly work with expressions that use data masking. This is true when you run the following example:

```r
wilcox.test(wage ~ jobclass, data = Wage) |> 
  report()

with(Wage, wilcox.test(wage ~ jobclass)) |> 
  report()

Wage |> 
  with(wilcox.test(wage ~ jobclass)) |> 
  report()
``` 

But working in R markdown output.

Is this actually a bug?

**Comment by mattansb** [comment] 2024-12-02 09:05
duplicate of #466 - see discussion there.

**Closed by mattansb** 2024-12-02 09:05 UTC

**Comment by rempsyc** [comment] 2024-12-10 03:29
@kisha126 htest objects do not contain the original data so it is not possible to recover it. However, you can provide the original data directly to `report`:

``` r
library(ISLR)
library(report)

wilcox.test(wage ~ jobclass, data = Wage) |> 
  report(data = Wage)
#> Effect sizes were labelled following Funder's (2019) recommendations.
#> 
#> The Wilcoxon rank sum test with continuity correction testing the difference in
#> ranks between wage and jobclass suggests that the effect is negative,
#> statistically significant, and medium (W = 8.53e+05, p < .001; r (rank
#> biserial) = -0.24, 95% CI [-0.28, -0.20])

with(Wage, wilcox.test(wage ~ jobclass)) |> 
  report(data = Wage)
#> Effect sizes were labelled following Funder's (2019) recommendations.
#> 
#> The Wilcoxon rank sum test with continuity correction testing the difference in
#> ranks between wage and jobclass suggests that the effect is negative,
#> statistically significant, and medium (W = 8.53e+05, p < .001; r (rank
#> biserial) = -0.24, 95% CI [-0.28, -0.20])

Wage |> 
  with(wilcox.test(wage ~ jobclass)) |> 
  report(data = Wage)
#> Effect sizes were labelled following Funder's (2019) recommendations.
#> 
#> The Wilcoxon rank sum test with continuity correction testing the difference in
#> ranks between wage and jobclass suggests that the effect is negative,
#> statistically significant, and medium (W = 8.53e+05, p < .001; r (rank
#> biserial) = -0.24, 95% CI [-0.28, -0.20])
```

<sup>Created on 2024-12-09 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by rempsyc** [comment] 2024-12-10 03:31
> But working in R markdown output.

Perhaps because you define the `data` object earlier in your rmarkdown script

**Comment by rempsyc** [comment] 2024-12-10 05:50
In version 0.5.9.1 available from GitHub, there should now be a clearer warning when the data argument is not available and not provided to report:

``` r
library(ISLR)
library(report)

wilcox.test(wage ~ jobclass, data = Wage) |> 
  report()
#> In the report() function, for htest objects, you can try providing the
#>   data argument manually, e.g., report(x, data = data).
#> Could not compute effectsize NA.
#>   Possible reason: Unable to retrieve data from htest object.
#>   Try using
#>   'rb()' directly.
#> Error in UseMethod("interpret"): no applicable method for 'interpret' applied to an object of class "NULL"
```

<sup>Created on 2024-12-10 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
